### ISSUE TITLE
Cannot deploy template - validating DNS names in form gives error.

### ISSUE THREAD

**Issue by twelling** [PaloAltoNetworks/azure#3]
When I try to this template I get an error will filling in the requested info on the first form where it requests storage accoutn name, resource group etc.

It hangs on the DNS names for the fw and the NATVM:

![screen shot 2016-09-21 at 21 36 25](https://cloud.githubusercontent.com/assets/22354421/18726224/c1136100-8043-11e6-8511-ca41d376e2bd.png)

In the region North Europe I see several instances of this template deployed so that means the prerequisite to deploy it via the marketplace once per region has already been fulfilled.

Is there a bug in this template, am I doing something wrong or is there an issue with Azure?

Thx,
Tom

**Comment by twelling** [comment]
Solved. Looks like the template/form has changed for me. Some kind of hiccup with Github or Azure Deploy TO procedure...

**Comment by jigarshah04** [comment]
Azure requires each VM's DNS name (including the regional prefix like <dnsname>.westus2.cloudapp.azure.com) to be globally unique.
