### ISSUE TITLE
Error when deploying using Powershell

### ISSUE THREAD

**Issue by Satarian23** [PaloAltoNetworks/azure#7]
Hello,

I am trying to deploy your AVSet template and when it tries I get the following error:

> New-AzureRmResourceGroupDeployment : 2:09:01 PM - Error: Code=InvalidTemplate; Message=Deployment template validation failed: 'The template parameters '**imageVersion, availabilitySetName**' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'location, vmName, imageSku, imageOffer, imagePublisher, nicName, vmSize, adminUsername, adminPassword, newStorageAccount, sshKey'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.

I checked the template file and the parameters file and I cannot find any issues.
The template file clearly identifies both of the parameters it is complaining about.

I can deploy this template fine if I use the web gui but not through powershell.
Let me know if you require further details

**Comment by Satarian23** [comment]
Looks like I found the problem.
In your template file: azureDeploy.json the baseURL default is "https://raw.githubusercontent.com/PaloAltoNetworks/azure/master/vmseries-avset"

In your parameters file: the baseURL default is "https://raw.githubusercontent.com/saurabhtrekker/UI1/master",

I didnt know which one was the correct URL so I went with the entry in the parameters file.
Once I switched the baseURL value to the "https://raw.githubusercontent.com/PaloAltoNetworks/azure/master/vmseries-avset" the template deployed correctly using powershell.

I don't know if you need to clean that up for noobs like me but I will mark this issue has closed.

**Comment by narayan-iyengar** [comment]
Thanks for pointing this out...fixed the issue
